spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:product-db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
